/**
 * Anomaly Alert Data Model
 * 
 * This module defines the structure of anomaly alerts generated by the
 * TrendAnalyzer when detecting unusual patterns in PII violation activity.
 */

/**
 * @typedef {'category_spike'|'new_category'|'critical_spike'|'ai_down_cluster'} AnomalyType
 */

/**
 * @typedef {'low'|'medium'|'high'} AnomalyMagnitude
 */

/**
 * @typedef {Object} AnomalyAlert
 * @property {AnomalyType} type - Type of anomaly detected
 * @property {string} detail - Human-readable description of the anomaly
 * @property {string} [affectedCategory] - PII category affected (for category_spike, new_category)
 * @property {string} [affectedSeverity] - Severity affected (for critical_spike)
 * @property {AnomalyMagnitude} magnitude - How unusual this pattern is
 * @property {number} windowSize - Number of records analyzed
 * @property {string} detectedAt - ISO 8601 timestamp of detection
 * @property {Object} summary - Statistical summary of the analysis window
 * @property {Object.<string, number>} summary.categoryCounts - Count of each PII category
 * @property {Object.<string, number>} summary.severityCounts - Count of each severity level
 * @property {Object} summary.aiAuditStats - AI audit status counts
 * @property {number} summary.aiAuditStats.audited - Number successfully audited by Gemini
 * @property {number} summary.aiAuditStats.failed - Number where Gemini failed
 */

/**
 * Validates an anomaly alert object.
 * 
 * @param {any} alert - Object to validate as AnomalyAlert
 * @returns {boolean} True if valid
 */
export function validateAnomalyAlert(alert) {
  if (!alert || typeof alert !== "object") return false;
  
  const required = [
    'type', 'detail', 'magnitude', 'windowSize', 'detectedAt', 'summary'
  ];
  
  for (const field of required) {
    if (!(field in alert)) return false;
  }
  
  // Type checks
  const validTypes = ["category_spike", "new_category", "critical_spike", "ai_down_cluster"];
  if (!validTypes.includes(alert.type)) return false;
  
  if (typeof alert.detail !== "string") return false;
  
  const validMagnitudes = ["low", "medium", "high"];
  if (!validMagnitudes.includes(alert.magnitude)) return false;
  
  if (typeof alert.windowSize !== "number") return false;
  if (typeof alert.detectedAt !== "string") return false;
  
  // Validate type-specific fields
  switch (alert.type) {
    case "category_spike":
    case "new_category":
      if (!alert.affectedCategory || typeof alert.affectedCategory !== "string") {
        return false;
      }
      break;
    case "critical_spike":
      if (!alert.affectedSeverity || alert.affectedSeverity !== "critical") {
        return false;
      }
      break;
    case "ai_down_cluster":
      // No additional required fields
      break;
  }
  
  // Validate summary structure
  if (!alert.summary || typeof alert.summary !== "object") return false;
  if (!alert.summary.categoryCounts || typeof alert.summary.categoryCounts !== "object") return false;
  if (!alert.summary.severityCounts || typeof alert.summary.severityCounts !== "object") return false;
  if (!alert.summary.aiAuditStats || typeof alert.summary.aiAuditStats !== "object") return false;
  
  if (typeof alert.summary.aiAuditStats.audited !== "number") return false;
  if (typeof alert.summary.aiAuditStats.failed !== "number") return false;
  
  return true;
}

/**
 * Format an anomaly alert for human-readable display.
 * 
 * @param {AnomalyAlert} alert - The alert to format
 * @returns {string} Formatted text representation
 */
export function formatAnomalyAlert(alert) {
  const lines = [
    `🚨 PII VIOLATION ANOMALY DETECTED`,
    `================================`,
    ``,
    `Type: ${alert.type.replace(/_/g, ' ').toUpperCase()}`,
    `Detail: ${alert.detail}`,
    `Magnitude: ${alert.magnitude.toUpperCase()}`,
    `Window Size: ${alert.windowSize} records`,
    `Detected At: ${alert.detectedAt}`,
    ``,
  ];
  
  if (alert.affectedCategory) {
    lines.push(`Affected Category: ${alert.affectedCategory}`);
  }
  
  if (alert.affectedSeverity) {
    lines.push(`Affected Severity: ${alert.affectedSeverity}`);
  }
  
  lines.push(``);
  lines.push(`📊 SUMMARY STATISTICS`);
  lines.push(`-------------------`);
  
  if (Object.keys(alert.summary.categoryCounts).length > 0) {
    lines.push(`Category Distribution:`);
    Object.entries(alert.summary.categoryCounts)
      .forEach(([category, count]) => {
        lines.push(`  ${category}: ${count}`);
      });
  } else {
    lines.push(`No PII categories detected`);
  }
  
  lines.push(``);
  
  const severityEntries = Object.entries(alert.summary.severityCounts)
    .filter(([_, count]) => count > 0);
  
  if (severityEntries.length > 0) {
    lines.push(`Severity Distribution:`);
    severityEntries.forEach(([severity, count]) => {
      lines.push(`  ${severity}: ${count}`);
    });
  } else {
    lines.push(`No severity data`);
  }
  
  lines.push(``);
  lines.push(`AI Audit Status:`);
  lines.push(`  Successfully audited: ${alert.summary.aiAuditStats.audited}`);
  lines.push(`  Failed audits: ${alert.summary.aiAuditStats.failed}`);
  
  return lines.join("\n");
}

/**
 * Get emoji for anomaly magnitude.
 * 
 * @param {AnomalyMagnitude} magnitude - The anomaly magnitude
 * @returns {string} Appropriate emoji
 */
export function getMagnitudeEmoji(magnitude) {
  switch (magnitude) {
    case "high": return "🔴";
    case "medium": return "🟠";
    case "low": return "🟡";
    default: return "⚠️";
  }
}

/**
 * Export type definitions for TypeScript/IDE support.
 */
export default {
  validateAnomalyAlert,
  formatAnomalyAlert,
  getMagnitudeEmoji,
};