/**
 * Remediation Report Data Model
 * 
 * This module defines the structure of remediation reports generated by the
 * RemediationAgent when investigating critical PII violations.
 */

/**
 * @typedef {Object} FixSuggestion
 * @property {string} rootCause - Brief analysis of why the PII violation occurred
 * @property {string} codeFix - Concrete code change suggestion for developers
 * @property {string} prevention - Long-term prevention strategy
 * @property {number} generatedAt - Timestamp when suggestion was generated
 */

/**
 * @typedef {Object} HistoricalOccurrence
 * @property {number} timestamp - Epoch timestamp of the occurrence
 * @property {string} logId - Unique identifier for the log entry
 */

/**
 * @typedef {Object} RemediationReport
 * @property {string} investigationId - Unique identifier for this investigation
 * @property {number} incidentTimestamp - When the critical violation occurred
 * @property {string} sourceService - Service that generated the log (or "unknown")
 * @property {string} violationCategory - Primary PII category (credit_card, ssn, etc.)
 * @property {'critical'|'high'|'medium'|'low'} severity - Violation severity
 * @property {number} historicalOccurrenceCount - How many times this pattern occurred in past 30d
 * @property {HistoricalOccurrence[]} mostRecentOccurrences - Up to 5 most recent occurrences
 * @property {FixSuggestion|null} fixSuggestion - AI-generated code fix suggestion
 * @property {string|null} aiError - Error message if AI suggestion generation failed
 * @property {number} reportGeneratedAt - When this report was assembled
 */

/**
 * Validates a remediation report object.
 * 
 * @param {any} report - Object to validate as RemediationReport
 * @returns {boolean} True if valid
 */
export function validateRemediationReport(report) {
  if (!report || typeof report !== "object") return false;
  
  const required = [
    'investigationId', 'incidentTimestamp', 'sourceService',
    'violationCategory', 'severity', 'historicalOccurrenceCount',
    'mostRecentOccurrences', 'reportGeneratedAt'
  ];
  
  for (const field of required) {
    if (!(field in report)) return false;
  }
  
  // Type checks
  if (typeof report.investigationId !== "string") return false;
  if (typeof report.incidentTimestamp !== "number") return false;
  if (typeof report.sourceService !== "string") return false;
  if (typeof report.violationCategory !== "string") return false;
  if (!['critical', 'high', 'medium', 'low'].includes(report.severity)) return false;
  if (typeof report.historicalOccurrenceCount !== "number") return false;
  if (!Array.isArray(report.mostRecentOccurrences)) return false;
  if (typeof report.reportGeneratedAt !== "number") return false;
  
  // Optional fields
  if (report.fixSuggestion !== null && report.fixSuggestion !== undefined) {
    if (typeof report.fixSuggestion !== "object") return false;
    if (typeof report.fixSuggestion.rootCause !== "string") return false;
    if (typeof report.fixSuggestion.codeFix !== "string") return false;
    if (typeof report.fixSuggestion.prevention !== "string") return false;
    if (typeof report.fixSuggestion.generatedAt !== "number") return false;
  }
  
  if (report.aiError !== null && report.aiError !== undefined) {
    if (typeof report.aiError !== "string") return false;
  }
  
  return true;
}

/**
 * Format a remediation report for human-readable display.
 * 
 * @param {RemediationReport} report - The report to format
 * @returns {string} Formatted text representation
 */
export function formatRemediationReport(report) {
  const lines = [
    `🔍 CRITICAL PII VIOLATION INVESTIGATION`,
    `========================================`,
    ``,
    `Investigation ID: ${report.investigationId}`,
    `Incident Time: ${new Date(report.incidentTimestamp).toISOString()}`,
    `Source Service: ${report.sourceService}`,
    `Violation Category: ${report.violationCategory}`,
    `Severity: ${report.severity}`,
    `Historical Occurrences (30d): ${report.historicalOccurrenceCount}`,
    ``,
  ];
  
  if (report.mostRecentOccurrences.length > 0) {
    lines.push(`Most Recent Occurrences:`);
    report.mostRecentOccurrences.forEach((occ, i) => {
      lines.push(`  ${i + 1}. ${new Date(occ.timestamp).toISOString()} (${occ.logId})`);
    });
    lines.push(``);
  }
  
  if (report.fixSuggestion) {
    lines.push(`💡 CODE FIX SUGGESTION`);
    lines.push(`---------------------`);
    lines.push(`Root Cause: ${report.fixSuggestion.rootCause}`);
    lines.push(``);
    lines.push(`Code Fix:`);
    lines.push(`  ${report.fixSuggestion.codeFix}`);
    lines.push(``);
    lines.push(`Prevention Strategy:`);
    lines.push(`  ${report.fixSuggestion.prevention}`);
    lines.push(``);
  } else if (report.aiError) {
    lines.push(`⚠️  AI SUGGESTION UNAVAILABLE`);
    lines.push(`---------------------------`);
    lines.push(`Error: ${report.aiError}`);
    lines.push(``);
  }
  
  lines.push(`Report Generated: ${new Date(report.reportGeneratedAt).toISOString()}`);
  
  return lines.join("\n");
}

/**
 * Export type definitions for TypeScript/IDE support.
 */
export default {
  validateRemediationReport,
  formatRemediationReport,
};